### ISSUE TITLE
Create gem

### ISSUE THREAD

**Issue by dazza-codes** [aaron-collier/hydra-packager#2]
Explore the results of using the bundle gem command, see
- http://bundler.io/man/bundle-gem.1.html
- http://guides.rubygems.org/

It will create the default gem structure and rake tasks for managing a ruby gem.  Then decide how to break out the current code in the rake task methods into the OOP code structure for the gem.  Explore using TDD to drive the refactoring from the rake tasks into the OOP ruby; see
- http://rspec.info/

**Comment by dazza-codes** [comment]
With regard to OOP in ruby, the Sandy Metz book is great, i.e.
- http://www.poodr.com/

**Comment by aaron-collier** [comment]
@darrenleeweber thanks, I'd done most of that but turned out the structure was one level up too high and wasn't getting picked up. Working now and should have a new gem ready soon.
